#!/usr/bin/env python3
"""Score Task1 pseudo labels generated by nnU-Net self-training teacher."""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path

import nibabel as nib
import numpy as np
from scipy import ndimage as ndi


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pseudo-dir", type=Path, default=Path("outputs/pseudo/task1_v17_high759"))
    parser.add_argument("--pred-dir", type=Path, default=None)
    parser.add_argument("--analysis-dir", type=Path, default=Path("outputs/analysis/task1_pseudo"))
    parser.add_argument("--top-k", type=int, nargs="+", default=[100, 200, 300])
    return parser.parse_args()


def summarize(values: list[float]) -> dict:
    arr = np.asarray(values, dtype=float)
    q1, q3 = np.percentile(arr, [25, 75])
    iqr = q3 - q1
    return {
        "min": float(arr.min()),
        "p01": float(np.percentile(arr, 1)),
        "p05": float(np.percentile(arr, 5)),
        "p25": float(q1),
        "median": float(np.median(arr)),
        "p75": float(q3),
        "p95": float(np.percentile(arr, 95)),
        "p99": float(np.percentile(arr, 99)),
        "max": float(arr.max()),
        "tukey_low": float(q1 - 1.5 * iqr),
        "tukey_high": float(q3 + 1.5 * iqr),
    }


def score_range(value: float, good_low: float, good_high: float, weak_low: float, weak_high: float) -> float:
    if good_low <= value <= good_high:
        return 1.0
    if weak_low <= value < good_low:
        return max(0.0, (value - weak_low) / max(good_low - weak_low, 1e-6))
    if good_high < value <= weak_high:
        return max(0.0, (weak_high - value) / max(weak_high - good_high, 1e-6))
    return 0.0


def component_stats(mask: np.ndarray) -> tuple[int, list[int]]:
    labeled, n_components = ndi.label(mask, structure=ndi.generate_binary_structure(mask.ndim, 1))
    if n_components == 0:
        return 0, []
    sizes = np.bincount(labeled.ravel())
    sizes[0] = 0
    return int(n_components), sorted((int(x) for x in sizes if x > 0), reverse=True)


def align_probability_to_mask(prob: np.ndarray, mask_shape: tuple[int, int, int]) -> np.ndarray:
    if tuple(prob.shape) == tuple(mask_shape):
        return prob
    transposed = np.transpose(prob, (2, 1, 0))
    if tuple(transposed.shape) == tuple(mask_shape):
        return transposed
    raise ValueError(f"Cannot align probability shape {prob.shape} to mask shape {mask_shape}")


def metadata_rows(path: Path) -> dict[str, dict]:
    rows = {}
    with path.open(encoding="utf-8") as f:
        for row in csv.DictReader(f):
            rows[row["case_id"]] = row
    return rows


def labeled_reference(mask_stats_csv: Path) -> dict:
    rows = []
    with mask_stats_csv.open(encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if row["source"] == "labeled_gt":
                rows.append(row)
    if not rows:
        raise RuntimeError(f"No labeled_gt rows in {mask_stats_csv}")
    return {
        "fg_voxels": summarize([float(row["fg_voxels"]) for row in rows]),
        "fg_ratio": summarize([float(row["fg_ratio"]) for row in rows]),
        "physical_volume_mm3": summarize([float(row["physical_volume_mm3"]) for row in rows]),
        "bbox_x": summarize([float(row["bbox_x"]) for row in rows]),
        "bbox_y": summarize([float(row["bbox_y"]) for row in rows]),
        "bbox_z": summarize([float(row["bbox_z"]) for row in rows]),
    }


def mask_record(case: dict, pred_dir: Path, metadata: dict, ref: dict) -> dict | None:
    nnunet_case_id = case["nnunet_case_id"]
    pred_path = pred_dir / f"{nnunet_case_id}.nii.gz"
    prob_path = pred_dir / f"{nnunet_case_id}.npz"
    if not pred_path.exists() or not prob_path.exists():
        return None

    img = nib.load(str(pred_path))
    mask = np.asanyarray(img.dataobj) > 0
    spacing = tuple(float(x) for x in img.header.get_zooms()[:3])
    fg_voxels = int(mask.sum())
    image_voxels = int(np.prod(mask.shape))
    physical_volume = float(fg_voxels * np.prod(spacing))
    components, sizes = component_stats(mask)
    largest = sizes[0] if sizes else 0
    second = sizes[1] if len(sizes) > 1 else 0
    largest_ratio = largest / fg_voxels if fg_voxels > 0 else 0.0

    probs = align_probability_to_mask(np.load(prob_path)["probabilities"][1], tuple(mask.shape))
    fg_probs = probs[mask]
    mean_fg_prob = float(fg_probs.mean()) if fg_probs.size else 0.0
    p05_fg_prob = float(np.percentile(fg_probs, 5)) if fg_probs.size else 0.0
    uncertain_ratio = float(np.mean((probs > 0.4) & (probs < 0.6)))

    meta = metadata[case["case_id"]]
    volume_score = score_range(
        physical_volume,
        ref["physical_volume_mm3"]["p05"],
        ref["physical_volume_mm3"]["p95"],
        ref["physical_volume_mm3"]["tukey_low"],
        ref["physical_volume_mm3"]["tukey_high"],
    )
    fg_ratio_score = score_range(
        fg_voxels / image_voxels if image_voxels else 0.0,
        ref["fg_ratio"]["p05"],
        ref["fg_ratio"]["p95"],
        ref["fg_ratio"]["tukey_low"],
        ref["fg_ratio"]["tukey_high"],
    )
    component_score = 1.0 if components <= 3 else (0.75 if components <= 5 else (0.4 if components <= 10 else 0.0))
    largest_score = score_range(largest_ratio, 0.999, 1.0, 0.995, 1.0)
    second_score = 1.0 if second <= 50 else (0.75 if second <= 100 else (0.3 if second <= 500 else 0.0))
    confidence_score = score_range(mean_fg_prob, 0.90, 1.0, 0.80, 1.0)
    boundary_score = 1.0 - min(1.0, uncertain_ratio / 0.01)
    metadata_score = 1.0 if meta["metadata_priority"] == "high" else (0.65 if meta["metadata_priority"] == "medium" else 0.2)

    quality_score = (
        0.25 * volume_score
        + 0.10 * fg_ratio_score
        + 0.15 * component_score
        + 0.15 * largest_score
        + 0.10 * second_score
        + 0.15 * confidence_score
        + 0.05 * boundary_score
        + 0.05 * metadata_score
    )

    return {
        "case_id": case["case_id"],
        "nnunet_case_id": nnunet_case_id,
        "source_image": case["source_image"],
        "pred_path": pred_path.as_posix(),
        "prob_path": prob_path.as_posix(),
        "metadata_priority": meta["metadata_priority"],
        "shape_x": int(mask.shape[0]),
        "shape_y": int(mask.shape[1]),
        "shape_z": int(mask.shape[2]),
        "spacing_x": spacing[0],
        "spacing_y": spacing[1],
        "spacing_z": spacing[2],
        "fg_voxels": fg_voxels,
        "fg_ratio": fg_voxels / image_voxels if image_voxels else 0.0,
        "physical_volume_mm3": physical_volume,
        "components": components,
        "largest_component": largest,
        "second_component": second,
        "largest_component_ratio": largest_ratio,
        "mean_fg_prob": mean_fg_prob,
        "p05_fg_prob": p05_fg_prob,
        "uncertain_ratio_04_06": uncertain_ratio,
        "volume_score": volume_score,
        "fg_ratio_score": fg_ratio_score,
        "component_score": component_score,
        "largest_score": largest_score,
        "second_score": second_score,
        "confidence_score": confidence_score,
        "boundary_score": boundary_score,
        "metadata_score": metadata_score,
        "quality_score": quality_score,
    }


def write_csv(path: Path, rows: list[dict]) -> None:
    if not rows:
        return
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def write_summary(path: Path, rows: list[dict], ref: dict, top_k: list[int]) -> None:
    lines = [
        "# Task1 pseudo-label quality summary",
        "",
        f"Scored cases: `{len(rows)}`",
        "",
        "## Labeled reference",
        "",
        "| Metric | p05 | median | p95 | tukey low | tukey high |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for key in ("physical_volume_mm3", "fg_voxels", "fg_ratio"):
        stats = ref[key]
        lines.append(
            f"| {key} | {stats['p05']:.6f} | {stats['median']:.6f} | {stats['p95']:.6f} | "
            f"{stats['tukey_low']:.6f} | {stats['tukey_high']:.6f} |"
        )

    lines.extend(
        [
            "",
            "## Top cases",
            "",
            "| Rank | Case | Score | Volume | Components | Largest ratio | Mean fg prob | Uncertain ratio |",
            "|---:|---|---:|---:|---:|---:|---:|---:|",
        ]
    )
    for idx, row in enumerate(rows[:30], start=1):
        lines.append(
            f"| {idx} | {row['case_id']} | {row['quality_score']:.6f} | "
            f"{row['physical_volume_mm3']:.1f} | {row['components']} | "
            f"{row['largest_component_ratio']:.6f} | {row['mean_fg_prob']:.6f} | "
            f"{row['uncertain_ratio_04_06']:.6f} |"
        )

    lines.extend(["", "## Top-k cutoffs", "", "| K | Score cutoff | Volume median | Mean fg prob median |", "|---:|---:|---:|---:|"])
    for k in top_k:
        subset = rows[: min(k, len(rows))]
        if not subset:
            continue
        lines.append(
            f"| {k} | {subset[-1]['quality_score']:.6f} | "
            f"{np.median([x['physical_volume_mm3'] for x in subset]):.1f} | "
            f"{np.median([x['mean_fg_prob'] for x in subset]):.6f} |"
        )
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    args = parse_args()
    pred_dir = args.pred_dir or (args.pseudo_dir / "pred")
    manifest_path = args.pseudo_dir / "manifest.json"
    if not manifest_path.is_file():
        raise FileNotFoundError(f"Missing manifest: {manifest_path}")
    metadata = metadata_rows(args.analysis_dir / "unlabeled_metadata_screen.csv")
    ref = labeled_reference(args.analysis_dir / "mask_stats.csv")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))["cases"]

    rows = []
    missing = []
    for case in manifest:
        row = mask_record(case, pred_dir, metadata, ref)
        if row is None:
            missing.append(case["nnunet_case_id"])
        else:
            rows.append(row)
    rows.sort(key=lambda x: x["quality_score"], reverse=True)

    args.analysis_dir.mkdir(parents=True, exist_ok=True)
    out_csv = args.analysis_dir / "pseudo_quality_v17_high759.csv"
    write_csv(out_csv, rows)
    for k in args.top_k:
        selected = rows[: min(k, len(rows))]
        (args.analysis_dir / f"pseudo_top{k}_cases.txt").write_text(
            "\n".join(row["case_id"] for row in selected) + ("\n" if selected else ""), encoding="utf-8"
        )
        (args.analysis_dir / f"pseudo_top{k}_nnunet_cases.txt").write_text(
            "\n".join(row["nnunet_case_id"] for row in selected) + ("\n" if selected else ""), encoding="utf-8"
        )
    (args.analysis_dir / "pseudo_quality_v17_high759_missing.json").write_text(
        json.dumps({"missing": missing}, indent=2), encoding="utf-8"
    )
    write_summary(args.analysis_dir / "pseudo_quality_v17_high759_summary.md", rows, ref, args.top_k)

    print(f"Scored: {len(rows)}")
    print(f"Missing: {len(missing)}")
    print(f"Wrote: {out_csv}")
    return 0 if not missing else 2


if __name__ == "__main__":
    raise SystemExit(main())
